#+OPTIONS: LaTeX:t          Do the right thing automatically (MathJax)
#+OPTIONS: LaTeX:dvipng     Force using dvipng images
#+OPTIONS: LaTeX:nil        Do not process LaTeX fragments at all
#+OPTIONS: LaTeX:verbatim   Verbatim export, for jsMath or so
#+ATTR_HTML: width="10in"

% org-export-with-LaTeX-fragments



README.org --- description



Copyright (C) 2015 Roman V. Prikhodchenko



Author: Roman V. Prikhodchenko <chujoii@gmail.com>



  This file is part of course_comp_net_inf_tech.

  course_comp_net_inf_tech is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  course_comp_net_inf_tech is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with course_comp_net_inf_tech.  If not, see <http://www.gnu.org/licenses/>.



* Keywords:
course network and information technologies
курс сетевые и информационные технологии



* Description:
курс "Компьютерные, сетевые и информационные технологии" (в расписании
курс называется "Компьютерные сетевые технологии" - видимо сократили).

Читается специальности "Электроэнергетика и электротехника" группа 21519
ПетрГУ в 2015 году с февраля по май (второй семестр пятого курса).

Предполагаемая нагрузка:
- лекций - 18 часов
- практических занятий - 18 часов
- консультаций - 2 часа
- зачёт - 2 часа



0. Git. Изучение системы контроля версий будет полезно всем (и мне в
   том числе), так как скорее всего студентам придётся работать с
   текстами (документами, программами, отчётами), а системы управления
   версиями позволяют этот процесс упорядочить.
2. Документация. (TeX, org-mode, markdown, конверторы, презентации).
1. Основы сетей и их построение. ModBus.  Реализация протокола
   передачи данных (как минимум будет полезна нескольким студентам).
   Однако в группе программировать умеют человек 5, для остальных
   это будет кошмаром.

* Usage:

читайте:
- [[course/01_vcs.org][Описание систем управления версиями]]
- [[course/02_git.org][основы git]]
- [[course/03_branch.org][ветвление git]]
- [[course/99_books.org][Литература]]




* History:
Project created at 2015-01(Jan)-12



* Dependences:


