* работа с версиями файлов
В большинстве случаев работа на компьютере заключается в с
информацией.  Информация в виде документов, изображений и прочего
хранится в файлах или базах данных (что по сути та же файловая система
только с особым языком запросов). Мы будем рассматривать только
текстовые файлы как наиболее простые.

В большинстве проектов возникает ситуация когда разработчик создающий
программы, разрабатывающий документацю, стандарты, ... приходит к
ситуации, когда:
- требуется создать тестовую версию, которую необходимо поддерживать
  параллельно с основной
- необходимо отчитаться о проделанной работе
- резервное копирование
- удалённая работа
- разработка не может продолжатья в одиночку (проект стал слишком
  большим) и дальнейшая разработка будет идти в коллективе

** Например *линейное* редактирование:
Если документ редактируется линейно, и включена "история изменений" в
текстовом процессоре то всё достаточно просто: Первый редактирует
документ. Другие ждут (они ведь не знают что он там напишет). Потом
второй принимает/непринимает изменения внесённые первым и опять
редактирует документ. Другие ждут. Первый принимает/непринимает
изменения внесённые вторым и опять редактирует документ. Остальные
ждут. Третий берётся подправить документ ... Все ждут.

Суть такова: пока один работает над документом остальные ждут для
соблюдения линейности.

** Пример нелинейного редактирования
Пока ещё дружный коллектив: Иванов, Петров, Сидоров.

Иванов разрабатывал документ и получилость 100 страниц мутного текста
пусть это будет версия A0.  Иванов отдал документ Петрову и Сидорову.
Все трое редактировали копии документа A0 одноверменно. У Иванова
получилась версия -> A1, у Петрова -> B1 а у Сидорова -> C1. Собрались
они вместе и сидят думают как им соединить все правки воедино.






* Определение
"Система управления версиями (от англ.  Version Control System, VCS
или Revision Control System) — программное обеспечение для облегчения
работы с изменяющейся информацией. Система управления версиями
позволяет хранить несколько версий одного и того же документа, при
необходимости возвращаться к более ранним версиям, определять, кто и
когда сделал то или иное изменение, и многое другое.

Такие системы наиболее широко используются при разработке программного
обеспечения для хранения исходных кодов разрабатываемой
программы. Однако они могут с успехом применяться и в других областях,
в которых ведётся работа с большим количеством непрерывно изменяющихся
электронных документов.  В частности, системы управления версиями
применяются в САПР, обычно в составе систем управления данными об
изделии (PDM). Управление версиями используется в инструментах
конфигурационного управления (Software Configuration Management
Tools).

Программное обеспечение Википедии ведёт историю изменений для всех её
статей, используя методы, аналогичные тем, которые применяются в
системах управления версиями."  [[https://ru.wikipedia.org/wiki/Система
управления версиями]]

1. Позволяют создавать разные варианты одного документа (ветки).
2. Предоставляют информацию о авторе, дате и изменениях в файле.
3. Ведут журнал изменений, в который пользователи могут записывать
   пояснения о том, что и почему они изменили в данной версии.
4. Контролируют права доступа пользователей, разрешая или запрещая
   чтение или изменение данных, в зависимости от того, кто запрашивает
   это действие.




